# Generated by Django 4.1.4 on 2022-12-09 09:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_created_at_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSubmition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='номер телефона')),
                ('code', models.CharField(default='1234', max_length=4)),
            ],
        ),
    ]
