# Generated by Django 4.1.4 on 2022-12-07 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('payment_method', models.CharField(blank=True, choices=[('cashless', 'Безналичный'), ('cash', 'Наличные')], db_index=True, max_length=12, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(choices=[('paid', 'Оплачен'), ('not_paid', 'Не оплачен')], db_index=True, default='not_paid', max_length=10, verbose_name='Статус оплаты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название процедуры')),
                ('descriptions', models.TextField(db_index=True, verbose_name='Описание')),
                ('image', models.ImageField(db_index=True, upload_to='', verbose_name='Изображение')),
                ('duration', models.CharField(db_index=True, max_length=255, verbose_name='Продолжительность')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название салона')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наимеование')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('foto', models.ImageField(db_index=True, upload_to='', verbose_name='Фотография')),
                ('reviews_qty', models.TextField(db_index=True, verbose_name='Отзыв')),
                ('experience', models.CharField(db_index=True, max_length=255, verbose_name='Опыт работы')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='beauty_salon.salon', verbose_name='Салон')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='beauty_salon.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(db_index=True, verbose_name='Время начала')),
                ('time_end', models.TimeField(db_index=True, verbose_name='Время окончания')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='beauty_salon.order', verbose_name='Заказ')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='beauty_salon.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beauty_salon.procedure', verbose_name='Процедура'),
        ),
        migrations.AddField(
            model_name='order',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beauty_salon.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Кто заказал'),
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beauty_salon.worker', verbose_name='Специалист'),
        ),
    ]
