# Generated by Django 4.1.4 on 2022-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(db_index=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
