# Generated by Django 4.1.4 on 2022-12-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0002_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(db_index=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
