# Generated by Django 4.1.4 on 2022-12-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0003_alter_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Категория услуг'),
        ),
    ]
