# Generated by Django 4.1.4 on 2022-12-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0004_alter_specialization_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialization',
            new_name='Category',
        ),
    ]
