# Generated by Django 4.1.4 on 2022-12-09 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0005_rename_specialization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='beauty_salon.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
