# Generated by Django 4.1.4 on 2022-12-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0006_procedure_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procedure',
            new_name='Service',
        ),
    ]
